FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install tzdata
RUN echo "America/Sao_Paulo" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
RUN apt-get -y install apache2 libapache2-mod-php php php-mbstring php-gd php-xml php-bcmath php-ldap php-mysql
ENV APACHE_LOCK_DIR="/var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="www-data"
ENV APACHE_RUN_GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2"

LABEL Description="Webserver"

Volume /var/www/

EXPOSE 80

RUN /etc/init.d/apache2 start
